# Generated by Django 5.0.4 on 2024-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_purchase_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
