# Generated by Django 5.0.4 on 2024-05-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_purchase_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
    ]
